
<?php
/**
 *  Magento 2.x Magento2x_RegistrationFormClone
 *
 * @Package    Magento2x_RegistrationFormClone
 * @Developer  Abdul Matin <matinict@gmail.com>
 * @Author     Matin(https://matinict.wordpress.com/)
 * @Dependency    SSLWireless Address(https://github.com/sslcommerz)
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


 ?>


 <h1><?php  //echo $this->getSellerTxt(); ?></h1>
